import assert from "node:assert/strict";
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { randomBytes } from "node:crypto";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import test from "node:test";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";

const home = mkdtempSync(join(tmpdir(), "aimcp-chat-archive-"));
process.env.HOME = home;
process.env.USERPROFILE = home;
process.env.CODING_MCP_LOG_TOOLS = "0";
const { createHttpServer } = await import("../dist/server/http-server.js");
const { createControllerHttpServer } = await import("../dist/control/http-server.js");
const { loadConfig } = await import("../dist/config/loader.js");
const { ProjectRegistry } = await import("../dist/projects/registry.js");
const { BindingStore } = await import("../dist/projects/bindings.js");
const { ProjectRuntimeManager } = await import("../dist/projects/runtime.js");
const { archiveProjectBindings, readConversation, saveConversationUse, conversationId, listConversationRecords } = await import("../dist/projects/conversations.js");
const { removeProject } = await import("../dist/control/services.js");
const { saveUserConfig } = await import("../dist/config/user-config.js");

test("client-uploaded chat is private, retry-safe, separate per client and retained after unbind/removal", async t => {
    saveUserConfig({ saveConversations: true });
    const registry = new ProjectRegistry({ projects: [] });
    const projects = [];
    for (const name of ["alpha", "beta"]) {
        const path = join(home, name); mkdirSync(path); writeFileSync(join(path, "keep.txt"), "keep");
        projects.push(await registry.register({ path }));
    }
    const bindings = new BindingStore({ bindings: [] });
    const runtime = createHttpServer(loadConfig({ projectRoot: home, local: true, userConfig: { port: 0 } }), {
        daemon: { registry, bindings, runtimes: new ProjectRuntimeManager(), controlToken: "fixture-control", runtimeIntent: { local: true, noTunnel: false, tunnelLogs: false }, tunnelStatus: () => ({ running: false, state: "off" }), onShutdown: async () => {} },
    });
    const controller = createControllerHttpServer({ state: { schemaVersion: 1, apiVersion: 1, pid: process.pid, host: "127.0.0.1", controlToken: randomBytes(32).toString("hex"), startedAt: new Date().toISOString(), version: "1.2.2" }, onShutdown: async () => {}, onReplaced: async () => {} });
    const client = new Client({ name: "archive-fixture", version: "1" });
    t.after(async () => { try { await client.close(); await runtime.close(); await controller.close(); } finally { rmSync(home, { recursive: true, force: true }); } });
    await runtime.listen(); await controller.listen();
    await client.connect(new StreamableHTTPClientTransport(new URL(runtime.getMcpUrl())));
    const call = args => client.callTool({ name: "project_control", arguments: { purpose: "Save visible conversation", ...args } });
    const select = async kind => {
        const result = await call({ action: "select", project_id: projects[0].id, client: kind });
        assert.equal(result.isError === true, false);
        return result.structuredContent.project_session;
    };
    const gpt = await select("chatgpt"); const gemini = await select("gemini");
    assert.notEqual(gpt, gemini);
    const messages = [{ id: "u1", role: "user", content: "fixture user visible message\n<img src=x onerror=alert(1)>" }, { id: "a1", role: "assistant", content: "fixture assistant visible answer" }];
    const record = handle => call({ action: "record", project_session: handle, messages, title: "本地测试聊天" });
    const first = await record(gpt);
    assert.equal(first.isError === true, false); assert.equal(first.structuredContent.saved_messages, 2);
    assert.equal(JSON.stringify(first).includes(messages[0].content), false);
    assert.equal((await record(gpt)).structuredContent.saved_messages, 0);
    assert.equal((await call({ action: "record", project_session: gpt, messages: [{ ...messages[0], content: "changed" }] })).isError, true);
    assert.equal((await call({ action: "select", project_session: gpt, project_id: projects[1].id, force: true, client: "gemini" })).isError, true);
    assert.equal((await call({ action: "current", project_session: gpt })).structuredContent.project.id, projects[0].id);
    await record(gemini);
    const oversized = [{ id: "big", role: "user", content: "中".repeat(16000) }, { id: "big2", role: "assistant", content: "中".repeat(16000) }];
    assert.equal((await call({ action: "record", project_session: gemini, messages: oversized })).isError, true);
    assert.equal((await call({ action: "record", messages })).isError, true);
    assert.equal((await call({ action: "record", project_session: "0".repeat(64), messages })).isError, true);
    const owner = bindings.resolveProjectSession("local:noauth", gpt).ownerKey;
    const gptId = conversationId(owner);
    const geminiId = conversationId(bindings.resolveProjectSession("local:noauth", gemini).ownerKey);
    const stored = readConversation(gptId);
    assert.equal(stored.client, "chatgpt"); assert.deepEqual(stored.messages, messages);
    assert.equal(readConversation(geminiId).client, "gemini");
    assert.equal(statSync(join(home, ".codex-mcp/conversations", gptId + ".json")).mode & 0o777, 0o600);
    assert.equal(readFileSync(join(home, ".codex-mcp/conversations", gptId + ".json"), "utf8").includes(owner), false);
    assert.throws(() => readConversation("../../outside"), /编号无效/);
    await Promise.all([saveConversationUse(owner, projects[0], { boundAt: stored.createdAt, messages: [{ id: "parallel-a", role: "user", content: "A" }] }), saveConversationUse(owner, projects[0], { boundAt: stored.createdAt, messages: [{ id: "parallel-b", role: "assistant", content: "B" }] })]);
    assert.equal(readConversation(gptId).messages.length, 4);
    const archiveModule = new URL("../dist/projects/conversations.js", import.meta.url).href;
    const childSource = `import {saveConversationUse} from ${JSON.stringify(archiveModule)}; const [owner, project, boundAt, prefix] = process.argv.slice(1); for(let i=0;i<5;i++) await saveConversationUse(owner, JSON.parse(project), {boundAt, messages:[{id:prefix+i,role:'user',content:'cross-process fixture'}]});`;
    await Promise.all(["writer-a-", "writer-b-"].map(prefix => promisify(execFile)(process.execPath, ["--input-type=module", "-e", childSource, owner, JSON.stringify(projects[0]), stored.createdAt, prefix], { timeout: 10000 })));
    assert.equal(readConversation(gptId).messages.length, 14);
    const base = `http://127.0.0.1:${controller.getPort()}`;
    assert.equal((await fetch(base + `/api/conversations/${gptId}`)).status, 401);
    const landing = await fetch(base);
    const cookie = landing.headers.get("set-cookie").split(";")[0];
    const csrf = (await landing.text()).match(/data-csrf-token="([^"]+)"/)[1];
    const headers = { cookie };
    const legacyOwner = "local:noauth|openai-session:legacy-read-only";
    await bindings.bind(legacyOwner, projects[1].id);
    await fetch(base + "/api/console/snapshot", { headers });
    assert.equal(existsSync(join(home, ".codex-mcp/conversations", conversationId(legacyOwner) + ".json")), false);
    await bindings.unbind(legacyOwner);
    const snapshot = await (await fetch(base + "/api/console/snapshot", { headers })).json();
    assert.equal(snapshot.conversationRecords.filter(item => item.client === "chatgpt").length, 1);
    assert.equal(snapshot.conversationRecords.filter(item => item.client === "gemini").length, 1);
    assert.equal(JSON.stringify(snapshot).includes("fixture user visible message"), false);
    const transcript = await (await fetch(base + `/api/conversations/${gptId}`, { headers })).json();
    assert.deepEqual(transcript.conversation.messages.slice(0, 2), messages);
    const endpoint = base + `/api/conversations/${gptId}`;
    assert.equal((await fetch(endpoint, { method: "DELETE" })).status, 401);
    assert.equal((await fetch(endpoint, { method: "DELETE", headers })).status, 403);
    assert.equal((await fetch(endpoint, { method: "DELETE", headers: { ...headers, "x-csrf-token": csrf, origin: "https://foreign.example" } })).status, 403);
    const deleteOptions = { method: "DELETE", headers: { ...headers, "x-csrf-token": csrf, origin: base } };
    assert.equal((await fetch(endpoint, deleteOptions)).status, 200);
    assert.equal(readConversation(gptId), undefined);
    assert.equal(existsSync(join(home, ".codex-mcp/conversations", gptId + ".json")), false);
    assert.equal(bindings.resolve(owner).projectId, projects[0].id);
    assert.equal(readConversation(geminiId).messages.length, 2);
    const deletedMarker = JSON.parse(readFileSync(join(home, ".codex-mcp/conversations", gptId + ".json.deleted"), "utf8"));
    assert.deepEqual(Object.keys(deletedMarker).sort(), ["client", "id", "schemaVersion"]);
    assert.equal(deletedMarker.client, "chatgpt");
    await archiveProjectBindings(projects[0], bindings.list());
    const erased = await (await fetch(base + "/api/console/snapshot", { headers })).json();
    assert.equal(erased.conversationRecords.some(item => item.id === gptId), false);
    assert.equal(erased.conversations.some(item => item.id === gptId), true);
    assert.equal((await fetch(endpoint, deleteOptions)).status, 200);
    assert.equal((await call({ action: "record", project_session: gpt, client: "gemini", messages })).isError, true);
    assert.equal((await record(gpt)).structuredContent.saved_messages, 2);
    assert.equal(readConversation(gptId).messages.length, 2);
    assert.equal(existsSync(join(home, ".codex-mcp/conversations", gptId + ".json.deleted")), false);
    assert.equal((await fetch(base + `/api/conversations/${geminiId}`, deleteOptions)).status, 200);
    const geminiDeleted = await (await fetch(base + "/api/console/snapshot", { headers })).json();
    assert.equal(geminiDeleted.conversations.find(item => item.id === geminiId).label, "Gemini 会话");
    assert.equal((await call({ action: "record", project_session: gemini, client: "chatgpt", messages })).isError, true);
    assert.equal((await record(gemini)).structuredContent.saved_messages, 2);
    assert.equal((await call({ action: "unbind", project_session: gpt })).isError === true, false);
    assert.equal(readConversation(gptId).messages.length, 2);
    assert.equal(listConversationRecords(bindings.list(), registry.list()).records.find(item => item.id === gptId).bound, false);
    await runtime.close();
    await removeProject(projects[0].id); // Deactivation retains metadata/chat and registration.
    assert.equal(readConversation(geminiId).messages.length, 2);
    await removeProject(projects[0].id, { forget: true });
    assert.equal(existsSync(join(projects[0].path, "keep.txt")), true);
    const after = await (await fetch(base + "/api/console/snapshot", { headers })).json();
    assert.equal(after.conversations.length, 0);
    assert.equal(after.conversationRecords.length, 2);
    assert.equal(after.conversationRecords.every(item => !item.bound && !item.registered), true);
    assert.equal((await (await fetch(base + `/api/conversations/${gptId}`, { headers })).json()).conversation.messages.length, 2);
    writeFileSync(join(home, ".codex-mcp/conversations", geminiId + ".json"), "corrupted fixture");
    const degraded = await (await fetch(base + "/api/console/snapshot", { headers })).json();
    assert.equal(degraded.unavailableConversationRecords, 1);
    assert.equal(degraded.conversationRecords.length, 1);
});
