import assert from "node:assert/strict";
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { randomBytes } from "node:crypto";
import test from "node:test";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";

const home = mkdtempSync(join(tmpdir(), "aimcp-recording-toggle-"));
process.env.HOME = home; process.env.USERPROFILE = home; process.env.CODING_MCP_LOG_TOOLS = "0";
const { loadConfig } = await import("../dist/config/loader.js");
const { loadUserConfig, saveUserConfig } = await import("../dist/config/user-config.js");
const { createHttpServer } = await import("../dist/server/http-server.js");
const { createControllerHttpServer } = await import("../dist/control/http-server.js");
const { ProjectRegistry } = await import("../dist/projects/registry.js");
const { BindingStore } = await import("../dist/projects/bindings.js");
const { ProjectRuntimeManager } = await import("../dist/projects/runtime.js");
const { saveConversationUse, conversationId, readConversation, archiveProjectBindings, listConversationRecords } = await import("../dist/projects/conversations.js");
const { presentBindings } = await import("../dist/control/project-selection.js");
const { loadBindingsFile } = await import("../dist/daemon/state.js");

test("recording switch persists, protects its API and stops Runtime archive writes without losing bindings or old chat", async t => {
    saveUserConfig({ saveConversations: true });
    const registry = new ProjectRegistry({ projects: [] });
    const path = join(home, "project"); mkdirSync(path);
    const project = await registry.register({ path });
    const owner = "local:noauth|openai-session:retained";
    const bindings = new BindingStore({ bindings: [] });
    await bindings.bind(owner, project.id);
    await saveConversationUse(owner, project, { boundAt: bindings.resolve(owner).boundAt, messages: [{ id: "old", role: "user", content: "existing chat" }] });
    const id = conversationId(owner);
    const archivePath = join(home, ".ai-mcp", "conversations", id + ".json");
    const original = readFileSync(archivePath, "utf8");
    const controller = createControllerHttpServer({ state: { schemaVersion: 1, apiVersion: 1, pid: process.pid, host: "127.0.0.1", controlToken: randomBytes(32).toString("hex"), startedAt: new Date().toISOString(), version: "1.2.2" }, onShutdown: async () => {}, onReplaced: async () => {} });
    const runtime = createHttpServer(loadConfig({ projectRoot: home, local: true, userConfig: { port: 0 } }), { daemon: { registry, bindings, runtimes: new ProjectRuntimeManager(), controlToken: "fixture-control", runtimeIntent: { local: true, noTunnel: true, tunnelLogs: false }, tunnelStatus: () => ({ running: false, state: "off" }), onShutdown: async () => {} } });
    const client = new Client({ name: "recording-toggle", version: "1" });
    t.after(async () => { try { await client.close(); await runtime.close(); await controller.close(); } finally { rmSync(home, { recursive: true, force: true }); } });
    await controller.listen(); await runtime.listen();
    await client.connect(new StreamableHTTPClientTransport(new URL(runtime.getMcpUrl())));
    const base = `http://127.0.0.1:${controller.getPort()}`;
    const landing = await fetch(base);
    const cookie = landing.headers.get("set-cookie").split(";")[0];
    const csrf = (await landing.text()).match(/data-csrf-token="([^"]+)"/)[1];
    const endpoint = base + "/api/conversations/recording";
    const options = { method: "PUT", headers: { cookie, origin: base, "x-csrf-token": csrf, "content-type": "application/json" }, body: JSON.stringify({ enabled: false }) };
    assert.equal((await fetch(endpoint, { ...options, headers: { "content-type": "application/json" } })).status, 401);
    assert.equal((await fetch(endpoint, { ...options, headers: { ...options.headers, "x-csrf-token": "wrong" } })).status, 403);
    assert.equal((await fetch(endpoint, { ...options, headers: { ...options.headers, origin: "https://foreign.example" } })).status, 403);
    for (const enabled of ["false", null, 0]) assert.equal((await fetch(endpoint, { ...options, body: JSON.stringify({ enabled }) })).status, 400);
    assert.equal((await fetch(endpoint, options)).status, 200);
    assert.equal(loadUserConfig().saveConversations, false);
    assert.throws(() => saveUserConfig({ saveConversations: "false" }), /boolean/);
    const call = args => client.callTool({ name: "project_control", arguments: { purpose: "Check recording preference", ...args } });
    const select = await call({ action: "select", project_id: project.id, client: "gemini" });
    assert.equal(select.isError === true, false);
    assert.equal(select.structuredContent.recording_enabled, false);
    const handle = select.structuredContent.project_session;
    const binding = bindings.resolveProjectSession("local:noauth", handle);
    assert.equal(existsSync(join(home, ".ai-mcp/conversations", conversationId(binding.ownerKey) + ".json")), false);
    assert.equal(presentBindings(loadBindingsFile()).find(item => item.id === conversationId(binding.ownerKey)).label, "Gemini 会话");
    const paused = await call({ action: "record", project_session: handle, messages: [{ id: "paused", role: "user", content: "DO NOT STORE" }] });
    assert.equal(paused.isError === true, false);
    assert.equal(paused.structuredContent.saved_messages, 0);
    assert.equal(paused.structuredContent.recording_enabled, false);
    assert.match(JSON.stringify(paused.content), /已关闭/);
    assert.equal(JSON.stringify(paused).includes("DO NOT STORE"), false);
    await saveConversationUse(owner, project, { boundAt: bindings.resolve(owner).boundAt, messages: [{ id: "new", role: "user", content: "DO NOT STORE" }] });
    await archiveProjectBindings(project, bindings.list());
    assert.equal(readFileSync(archivePath, "utf8"), original);
    assert.equal(listConversationRecords(bindings.list(), registry.list()).records.length, 1);
    const snapshot = await (await fetch(base + "/api/console/snapshot", { headers: { cookie } })).json();
    assert.equal(snapshot.setup.config.saveConversations, false);
    assert.equal(snapshot.conversations.length, 2);
    assert.equal(snapshot.conversationRecords.length, 1);
    assert.equal((await call({ action: "record", project_session: handle, client: "chatgpt", messages: [{ id: "wrong", role: "user", content: "wrong" }] })).isError, true);
    assert.equal((await fetch(endpoint, { ...options, body: JSON.stringify({ enabled: true }) })).status, 200);
    const resumed = await call({ action: "record", project_session: handle, messages: [{ id: "resumed", role: "user", content: "new visible message" }] });
    assert.equal(resumed.structuredContent.saved_messages, 1);
    assert.equal(resumed.structuredContent.recording_enabled, true);
    const record = readConversation(conversationId(binding.ownerKey));
    assert.equal(record.client, "gemini");
    assert.deepEqual(record.messages.map(item => item.id), ["resumed"]);
    assert.equal(readConversation(id).messages.length, 1);
});
